spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/craft_trade_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.crafts.platform.entity

server:
  port: 8080
